### ISSUE TITLE
The method isVisible(selector[, options]) from a Page object throws an exception.

### ISSUE THREAD

**Issue by Uva-h** [grafana/xk6-browser#939] opened 2023-06-16 15:47 UTC
### Brief summary

The method isVisible(selector[, options]) from a Page object throws an exception when the given selector is not found instead of returning the boolean false which is the expected outcome.

### xk6-browser version

latest/main

### OS

Windows 11

### Chrome version

114.0.5735.134 

### Steps to reproduce the problem

page.isVisible("//h1[contains(text(),'This string doesn't exists')]");

### Expected behaviour

For a boolean false statement to be return and the code to continue execution.

### Actual behaviour

Function throws an exception and stops execution.

**Comment by ka3de** [comment] 2023-08-08 09:09
Closing as duplicate of https://github.com/grafana/xk6-browser/issues/981.

**Closed by ka3de** 2023-08-08 09:09 UTC
Labels: bug
