### ISSUE TITLE
`browser_first_meaningful_paint` doesn't get reported all the time

### ISSUE THREAD

**Issue by mdcruz** [grafana/xk6-browser#573] opened 2022-10-07 13:03 UTC
When running this [example script](https://github.com/grafana/xk6-browser/blob/main/examples/fillform.js), I notice that it doesn't report `browser_first_meaningful_paint`

<img width="1005" alt="Screenshot 2022-10-07 at 13 58 27" src="https://user-images.githubusercontent.com/10811379/194559411-c1a65d17-5e4b-4fac-b67b-381380d941e8.png">

If I add the `slowMo` option and set it to `30ms` or more,`browser_first_meaningful_paint` is reported.

<img width="1081" alt="Screenshot 2022-10-07 at 14 02 52" src="https://user-images.githubusercontent.com/10811379/194560173-9f9eb315-5f7d-4703-b1b3-14040e94f55d.png">

When `25ms` is used, it intermittently reports this metric.

Maybe related to [this comment](https://github.com/grafana/xk6-browser/issues/191#issuecomment-1086016760).

**Comment by ka3de** [comment] 2023-01-26 10:28
A few notes after an initial research on this problem:

First of all, I was able to reproduce this issue with the current implementation ([5bd4fa1](https://github.com/grafana/xk6-browser/tree/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2)) and current version of the [script](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/examples/fillform.js) referenced in the issue description.

My **first theory**, as suggested by the issue description and this [comment](https://github.com/grafana/xk6-browser/issues/191#issuecomment-1086016760) was that there could be a racy situation between the `firstMeaningfulPaint` event and the `initTime` for the frame. So effectively reaching [this point](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/frame.go#L244-L249) and ignoring the emission of the metric.
Adding a log message at that point showed that no metric was being ignored for that condition.

Instead, looking for [this log line](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/frame.go#L240) in `Frame.emitMetric` method, I could see that no call was made for that method for the `firstMeaningfulPaint` event when the issue was reproduced. Neither [this log line](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/frame_session.go#L713) from `FrameSession.onPageLifeCycle` was logged for that event even thought we are correctly subscribing to it on frame session [init](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/frame_session.go#L465).

Comparing a debug level log for a correct execution with an incorrect one I could see that:
- The correct execution log shows: 4 occurrences for `event:firstMeaningfulPaintCandidate` and 1 occurrence for `event:firstMeaninfulPaint`
- The incorrect execution log shows: 4 occurrences for `event:firstMeaningfulPaintCandidate` and 0 for `event:firstMeaningfulPaint`

See incorrect execution log: [err.log](https://github.com/grafana/xk6-browser/files/10508178/err.log)
See correct execution log: [ok.log](https://github.com/grafana/xk6-browser/files/10508182/ok.log)

Once **discarded the initial theory**, I was wondering if we could be somehow mishandling the `firstMeaningFulPaint` event at a previous point before reaching frame session. Therefore I decided to use the [trace log](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/connection.go#L292) defined at the connection level in order to log every message read from the browser through CDP websocket.

The behavior observed was the same as with the initial test, but this time checked at the connection level:
- The correct execution log shows: 4 occurrences for `event:firstMeaningfulPaintCandidate` and 1 occurrence for `event:firstMeaninfulPaint` at the connection level
- The incorrect execution log shows: 4 occurrences for `event:firstMeaningfulPaintCandidate` and 0 for `event:firstMeaningfulPaint`

See incorrect execution trace log: [trace_err.log](https://github.com/grafana/xk6-browser/files/10508277/trace_err.log)
See correct execution trace log: [trace_ok.log](https://github.com/grafana/xk6-browser/files/10508279/trace_ok.log)

This, I understand discards some mishandling of the event from our side between when the message is received from CDP websocket and when it's emitted.

All in all, by intuition I would say that one possibility is that we are stopping/closing some event handling loop too early and we are missing on the `firstMeaningfulPaint` event. This explains the fact that, as indicated by @mdcruz in the issue description, using `slowMo` seemed to fix the problem; and also the fact that, as per my tests, using a higher debug level makes the issue harder to reproduce (as in higher log level implies more time spent logging and therefore slower execution).

**Current theories and next steps:**
- Are we at some point stopping receiving events "too early"?
- Could this be a problem in `chromedp` implementation?
- Could this be some tricky situation in browser / CDP that we are not aware of? For which maybe the event is not fired in some situations?

**Comment by ankur22** [comment] 2023-01-26 15:44
My vote would be to remove this since it's no longer available in Chrome Dev Tools in the performance tab, as well it being deprecated in lighthouse. It's also not available in all browsers, as well as the metric value differing from one browser to another browser.

We should instead priortise getting Web Vitals into xk6-browser.

**Comment by inancgumus** [comment] 2023-01-30 11:50
@ankur22,

I agree that we can prioritize and get to Web Vitals (more accurately: after switching to [LCP](https://web.dev/lcp/)). However, I would rather wait and remove this metric after we have proper Web Vitals support in place so that we can do the removal. Let's not remove something we have until we have a better alternative in place.

By the way, asking out of curiosity, from the Chromium issue you shared, it seems, they haven't finished and shipped the deprecation "feature" yet, haven't they? Also, Lighthouse deprecates it because the metric needs to provide a standardized way of measurement, but it does not. As I said, irrelevant of these, I agree that we should get to Web Vitals.

**Comment by ankur22** [comment] 2023-01-30 12:03
Yep, happy to leave it in as is, and we can remove it once we start working on Web Vitals.

**Comment by inancgumus** [comment] 2023-01-30 12:26
👍 Alright, I'm closing this one as not planned (this one is not planned, but the task in Web Vitals is planned).

**Closed by inancgumus** 2023-01-30 12:26 UTC
Labels: bug, evaluation needed
