### ISSUE TITLE
Data race in TestWaitForFrameNavigationWithinDocument: NavigateFrame

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#254] opened 2022-02-25 10:12 UTC
[This CI job](https://github.com/grafana/xk6-browser/runs/5331842835?check_suite_focus=true) has failed with a data race error. It seems sharing of a `Request` concurrently is causing the issue.

<details>
<summary>Click here to see the log output.</summary>

```shell
Read at 0x00c0075f7318 by goroutine 2552:
  github.com/grafana/xk6-browser/common.(*FrameManager).NavigateFrame()
      /home/runner/work/xk6-browser/xk6-browser/common/frame_manager.go:677 +0x151d
  github.com/grafana/xk6-browser/common.(*Frame).Goto()
      /home/runner/work/xk6-browser/xk6-browser/common/frame.go:843 +0x6c
  github.com/grafana/xk6-browser/common.(*Page).Goto()
      /home/runner/work/xk6-browser/xk6-browser/common/page.go:555 +0x1d3
  github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1()
      /home/runner/work/xk6-browser/xk6-browser/tests/frame_manager_test.go:29 +0x137
  testing.tRunner()
      /home/runner/sdk/gotip/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/runner/sdk/gotip/src/testing/testing.go:1486 +0x47

Previous write at 0x00c0075f7318 by goroutine 2667:
  github.com/grafana/xk6-browser/common.(*NetworkManager).handleRequestRedirect()
      /home/runner/work/xk6-browser/xk6-browser/common/network_manager.go:311 +0x95
  github.com/grafana/xk6-browser/common.(*NetworkManager).onRequest()
      /home/runner/work/xk6-browser/xk6-browser/common/network_manager.go:442 +0x114
  github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents()
      /home/runner/work/xk6-browser/xk6-browser/common/network_manager.go:377 +0x29e
  github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
      /home/runner/work/xk6-browser/xk6-browser/common/network_manager.go:356 +0x3e

Goroutine 2552 (running) created at:
  testing.(*T).Run()
      /home/runner/sdk/gotip/src/testing/testing.go:1486 +0x724
  github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument()
      /home/runner/work/xk6-browser/xk6-browser/tests/frame_manager_test.go:24 +0x1b1
  testing.tRunner()
      /home/runner/sdk/gotip/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/runner/sdk/gotip/src/testing/testing.go:1486 +0x47

Goroutine 2667 (running) created at:
  github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents()
      /home/runner/work/xk6-browser/xk6-browser/common/network_manager.go:355 +0x324
  github.com/grafana/xk6-browser/common.NewNetworkManager()
      /home/runner/work/xk6-browser/xk6-browser/common/network_manager.go:110 +0x57d
  github.com/grafana/xk6-browser/common.NewFrameSession()
      /home/runner/work/xk6-browser/xk6-browser/common/frame_session.go:120 +0x675
  github.com/grafana/xk6-browser/common.NewPage()
      /home/runner/work/xk6-browser/xk6-browser/common/page.go:130 +0xba6
  github.com/grafana/xk6-browser/common.(*Browser).onAttachedToTarget()
      /home/runner/work/xk6-browser/xk6-browser/common/browser.go:278 +0xaa4
  github.com/grafana/xk6-browser/common.(*Browser).initEvents.func1()
      /home/runner/work/xk6-browser/xk6-browser/common/browser.go:180 +0x46c
```

</details>

Suspicious lines of code:

https://github.com/grafana/xk6-browser/blob/ae264530b6fbe0285ac9df9b0f4a907b460bb805/common/frame_manager.go#L674-L681

and

https://github.com/grafana/xk6-browser/blob/ae264530b6fbe0285ac9df9b0f4a907b460bb805/common/network_manager.go#L437-L444

Maybe related for inspiration: https://github.com/grafana/xk6-browser/pull/204#discussion_r796654388.

Related: #252

**Comment by imiric** [comment] 2022-02-25 11:07
Let's leave this open for a while until we're sure it doesn't happen again.

**Comment by inancgumus** [comment] 2022-03-07 09:23
This still regresses (try on cb45218):

```shell
==================
WARNING: DATA RACE
Read at 0x00c007dbd530 by goroutine 2205:
  runtime.mapaccess1()
      /usr/local/go/src/runtime/map.go:394 +0x28c
  github.com/dop251/goja.(*Runtime).typeInfo()
      /Users/inanc/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220110113543-261677941f3c/object_goreflect.go:504 +0x70
  github.com/dop251/goja.(*objectGoReflect).init()
      /Users/inanc/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220110113543-261677941f3c/object_goreflect.go:112 +0x6f4
  github.com/dop251/goja.(*Runtime).ToValue()
      /Users/inanc/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220110113543-261677941f3c/runtime.go:1798 +0x28a4
  go.k6.io/k6/js/common.Throw()
      /Users/inanc/go/pkg/mod/go.k6.io/k6@v0.36.0/js/common/util.go:36 +0x70
  github.com/grafana/xk6-browser/common.k6Throw()
      /Users/inanc/grafana/k6b/common/helpers.go:214 +0x200
  github.com/grafana/xk6-browser/common.(*FrameManager).WaitForFrameNavigation()
      /Users/inanc/grafana/k6b/common/frame_manager.go:721 +0x880
  github.com/grafana/xk6-browser/common.(*Frame).WaitForNavigation()
      /Users/inanc/grafana/k6b/common/frame.go:1459 +0x190
  github.com/grafana/xk6-browser/common.(*Page).WaitForNavigation()
      /Users/inanc/grafana/k6b/common/page.go:881 +0x138
  github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1.2.1()
      /Users/inanc/grafana/k6b/tests/frame_manager_test.go:49 +0x12c
  github.com/stretchr/testify/assert.didPanic.func1()
      /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1018 +0x70
  github.com/stretchr/testify/assert.didPanic()
      /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1020 +0x54
  github.com/stretchr/testify/assert.NotPanics()
      /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1091 +0x68
  github.com/stretchr/testify/require.NotPanics()
      /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/require/require.go:1456 +0xb0
  github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1.2()
      /Users/inanc/grafana/k6b/tests/frame_manager_test.go:48 +0x138

Previous write at 0x00c007dbd530 by goroutine 2224:
  runtime.mapaccessK()
      /usr/local/go/src/runtime/map.go:511 +0x1ec
  github.com/dop251/goja.(*Runtime).typeInfo()
      /Users/inanc/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220110113543-261677941f3c/object_goreflect.go:509 +0x15c
  github.com/dop251/goja.(*objectGoReflect).init()
      /Users/inanc/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220110113543-261677941f3c/object_goreflect.go:112 +0x6f4
  github.com/dop251/goja.(*Runtime).ToValue()
      /Users/inanc/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220110113543-261677941f3c/runtime.go:1798 +0x28a4
  github.com/grafana/xk6-browser/common.(*ElementHandle).eval()
      /Users/inanc/grafana/k6b/common/element_handle.go:1455 +0x1b4
  github.com/grafana/xk6-browser/common.(*ElementHandle).evalWithScript()
      /Users/inanc/grafana/k6b/common/element_handle.go:1442 +0x26c
  github.com/grafana/xk6-browser/common.(*ElementHandle).checkHitTargetAt()
      /Users/inanc/grafana/k6b/common/element_handle.go:251 +0x1b0
  github.com/grafana/xk6-browser/common.getElementHandlePointerActionFn.func1()
      /Users/inanc/grafana/k6b/common/element_handle.go:172 +0x484
  github.com/grafana/xk6-browser/common.framePointerActionFn.func1()
      /Users/inanc/grafana/k6b/common/frame.go:1618 +0x18c

Goroutine 2205 (running) created at:
  github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1()
      /Users/inanc/grafana/k6b/tests/frame_manager_test.go:47 +0x2f0
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x198

Goroutine 2224 (running) created at:
  github.com/grafana/xk6-browser/common.callApiWithTimeout()
      /Users/inanc/grafana/k6b/common/helpers.go:110 +0x108
  github.com/grafana/xk6-browser/common.(*Frame).Click()
      /Users/inanc/grafana/k6b/common/frame.go:674 +0x534
  github.com/grafana/xk6-browser/common.(*Page).Click()
      /Users/inanc/grafana/k6b/common/page.go:398 +0x1a8
  github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1.1()
      /Users/inanc/grafana/k6b/tests/frame_manager_test.go:43 +0x6c
==================
--- FAIL: TestWaitForFrameNavigationWithinDocument (1.51s)
    --- FAIL: TestWaitForFrameNavigationWithinDocument/history (1.51s)
        frame_manager_test.go:48: 
                Error Trace:    frame_manager_test.go:48
                                                        asm_arm64.s:1133
                Error:          func (assert.PanicTestFunc)(0x105e2ed20) should not panic
                                        Panic value:    waitForFrameNavigation timed out after 600ms
                                        Panic stack:    goroutine 13222 [running]:
                                runtime/debug.Stack()
                                        /usr/local/go/src/runtime/debug/stack.go:24 +0x94
                                github.com/stretchr/testify/assert.didPanic.func1.1(0xc008c03e48, 0xc008c03e16, 0xc008c03e38)
                                        /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1013 +0xb8
                                panic({0x106230340, 0xc0089f9020})
                                        /usr/local/go/src/runtime/panic.go:1052 +0x2ac
                                go.k6.io/k6/js/common.Throw(0xc001143880, {0x10627f6e0, 0xc0089f6bb0})
                                        /Users/inanc/go/pkg/mod/go.k6.io/k6@v0.36.0/js/common/util.go:36 +0x8c
                                github.com/grafana/xk6-browser/common.k6Throw({0x10629bc60, 0xc007fa97a0}, {0x105e6a55c, 0x29}, {0xc002b45b38, 0x1, 0x1})
                                        /Users/inanc/grafana/k6b/common/helpers.go:214 +0x204
                                github.com/grafana/xk6-browser/common.(*FrameManager).WaitForFrameNavigation(0xc000fdcd10, 0xc00843a340, {0x1062b2678, 0xc0088451d0})
                                        /Users/inanc/grafana/k6b/common/frame_manager.go:721 +0x884
                                github.com/grafana/xk6-browser/common.(*Frame).WaitForNavigation(...)
                                        /Users/inanc/grafana/k6b/common/frame.go:1459
                                github.com/grafana/xk6-browser/common.(*Page).WaitForNavigation(0xc0027b2a00, {0x1062b2678, 0xc0088451d0})
                                        /Users/inanc/grafana/k6b/common/page.go:881 +0x194
                                github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1.2.1()
                                        /Users/inanc/grafana/k6b/tests/frame_manager_test.go:49 +0x130
                                github.com/stretchr/testify/assert.didPanic.func1(0xc008566e48, 0xc008566e16, 0xc008566e38, 0xc0088451a0)
                                        /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1018 +0x74
                                github.com/stretchr/testify/assert.didPanic(0xc0088451a0)
                                        /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1020 +0x58
                                github.com/stretchr/testify/assert.NotPanics({0x1062843a0, 0xc002d3a820}, 0xc0088451a0, {0x0, 0x0, 0x0})
                                        /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1091 +0x6c
                                github.com/stretchr/testify/require.NotPanics({0x106293c60, 0xc002d3a820}, 0xc0088451a0, {0x0, 0x0, 0x0})
                                        /Users/inanc/go/pkg/mod/github.com/stretchr/testify@v1.7.0/require/require.go:1456 +0xb4
                                github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1.2(0xc002d3a820, {0x1062bfbb0, 0xc0027b2a00}, 0xc002882f60, 0xc003366b28, 0xc007eff920)
                                        /Users/inanc/grafana/k6b/tests/frame_manager_test.go:48 +0x13c
                                created by github.com/grafana/xk6-browser/tests.TestWaitForFrameNavigationWithinDocument.func1
                                        /Users/inanc/grafana/k6b/tests/frame_manager_test.go:47 +0x2f4
                Test:           TestWaitForFrameNavigationWithinDocument/history
        frame_manager_test.go:59: Test timed out
        testing.go:1152: race detected during execution of test
    testing.go:1152: race detected during execution of test
```

**Comment by inancgumus** [comment] 2022-03-07 09:28
`TestWaitForFrameNavigationWithinDocument/history` also timed out here: https://github.com/grafana/xk6-browser/runs/5445862869?check_suite_focus=true

**Comment by inancgumus** [comment] 2022-03-10 08:58
Another time out: https://github.com/grafana/xk6-browser/runs/5493049491?check_suite_focus=true

**Comment by imiric** [comment] 2022-03-10 10:49
@inancgumus That's a different data race from the one reported in the issue description. It's also a general one that can happen with any test, see [this comment](https://github.com/grafana/xk6-browser/pull/263#pullrequestreview-905621976).

It boils down to the Goja runtime not being thread safe, and us pretty liberally reusing it for all kinds of things (`rt.ToValue()`, etc.). I think the fix for this is decoupling our JS layer, as we discussed, and making sure that we don't use Goja in internal methods like `ElementHandle.eval()`.

The timeouts are weird, since they're not the short ones that exceed the `waitForNavigation` timeout, which #252 aimed to fix, but they're the [30s `navigationTimeout`](https://github.com/grafana/xk6-browser/blob/3ad187ce3f3cd07fd572bb504f8a69d28cf29d4f/tests/test_browser.go#L267), which means `Page.Goto()` is timing out. I'm not clear why that would happen... :confused: It's only reproducible in CI, so my guess is the usual flakiness of these machines. We should run with `XK6_BROWSER_LOG=trace` and try to see what's happening.

**Comment by inancgumus** [comment] 2022-03-10 10:59
Why don't we change the issue title and collect everything under this issue as the new issues will disperse information more? It seems like the errors are coming from the same test.

> I think the fix for this is decoupling our JS layer, as we discussed, ...

Yeah, like we discussed (https://github.com/grafana/xk6-browser/pull/268#discussion_r822566026), I created a separate issue for it #271.

> making sure that we don't use Goja in internal methods like ElementHandle.eval().

Can you expand a bit more on this one, maybe in issue #271?

> We should run with XK6_BROWSER_LOG=trace and try to see what's happening.

+1

**Comment by imiric** [comment] 2022-03-10 11:21
> Why don't we change the issue title and collect everything under this issue as the new issues will disperse information more?

I'm not a fan of repurposing issues, as it expands their scope and we can't be sure if they can be closed. This issue already is only open because we're waiting to see if that specific data race is fixed. So far I don't think we've encountered it again, so please open new issues if they clearly don't have the same cause.

**Comment by inancgumus** [comment] 2022-03-10 11:25
Data races can also cause timeouts because of unknown reasons. Let's move it to another issue since you insist :-)

**Comment by imiric** [comment] 2022-08-11 12:29
We haven't run into this issue recently, and the recent refactoring should've improved the situation. So we're closing this, but if it pops up again we can reopen it.

**Closed by imiric** 2022-08-11 12:29 UTC
Labels: bug
