### ISSUE TITLE
Existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by vishruth143** [grafana/xk6-browser#613] opened 2022-10-27 19:50 UTC
### Brief summary

Getting the below issue while running the below script on windows 10 machine.

"Existing connection was forcibly closed by the remote host"

**Chrome Browser Version:** Version 106.0.5249.119 (Official Build) (64-bit)
**xk6-browser version:** V0.5.0

You can find more details on this issue in the below forum post:
https://community.k6.io/t/existing-connection-was-forcibly-closed-by-the-remote-host/4990/1

```js
import { chromium } from 'k6/x/browser';

export default function () {
  const browser = chromium.launch({
    headless: true,
    slowMo: '1s',
  });
  const context = browser.newContext();
  const page = context.newPage();

  // 01. Go to the openidconnect landing page and click on CONFIGURATION
  page.goto('https://openidconnect.net/', { waitUntil: 'networkidle' }).then(() => {    
    page.screenshot({ path: 'screenshots/01_screenshot.png' });
    page.waitForSelector('button[class="playground-header-config btn btn-link"]');        
    return page.click('button[class="playground-header-config btn btn-link"]');
  }).then(() => {    
    page.screenshot({ path: 'screenshots/02_screenshot.png' });   
    page.waitForSelector("select[name='server']"); 
    page.selectOption("select[name='server']", "custom");
    page.screenshot({ path: 'screenshots/03_screenshot.png' });
    page.type("input[placeholder='https://my-oidc.com/.well-known/openid-configuration']", 'https://my-oidc.com/.well-known/openid-configuration');
    page.screenshot({ path: 'screenshots/04_screenshot.png' });
  }).finally(() => {
    page.close();
    browser.close();
  });
}
```

### xk6-browser version

v0.5.0

### OS

Windows 10

### Chrome version

Version 106.0.5249.119 (Official Build) (64-bit)

### Steps to reproduce the problem

Run the script given in headless mode using chrome browser on windows 10 machine.

### Expected behaviour

The script should click on CONFIGIRATION and type the URL.

### Actual behaviour

The URL given is not typed to the textbox.

**Comment by vishruth143** [comment] 2022-11-01 17:29
> @vishruth143 - Any Update from K6 Team? as we see same issue when we execute the script.

@malliarjun440 Below is the reply I got from the K6 team. 
We’ll consider it in the next planning session (next week or so).

https://community.k6.io/t/existing-connection-was-forcibly-closed-by-the-remote-host/4990/16

**Comment by sinanve** [comment] 2023-01-11 13:17
also suffering the same issue here, Our dashboard is also opening slowly and before it is opened, i am getting the same error before browser is closed

**Comment by ankur22** [comment] 2023-01-27 10:18
I'm closing this issue for now, as I can't reproduce the original issue. Please reopen it if you're still having the same issue.

**Closed by ankur22** 2023-01-27 10:18 UTC
Labels: bug, awaiting user

**Comment by crisreekoh** [comment] 2023-06-30 07:15
> also suffering the same issue here, Our dashboard is also opening slowly and before it is opened, i am getting the same error before browser is closed

Same, my end2end load testing will page will open only the 1st and 2nd page then the browser page will terminate prematurely. 
`ERRO[0032] communicating with browser: write tcp 127.0.0.1:55974->127.0.0.1:55973: wsasend: An existing connection was forcibly closed by the remote host.  category=cdp elapsed="2244 ms" goroutine=79`

**Comment by ankur22** [comment] 2023-06-30 12:43
@crisreekoh can you provide us with the following to be able to diagnose this issue?:

Which xk6-browser version you are using.
Which OS you are running on your computer.
The test script pointing to a publicly accessible website.
The exact error message you are seeing when you try and run the test.

Have you checked out our [community forum](https://community.k6.io/c/k6-browser/14) to see if your question has already been answered?

**Comment by crisreekoh** [comment] 2023-07-03 02:33
Hi @ankur22 

**Which xk6-browser version you are using.** 
- k6 v0.45.0 (2023-06-19T08:41:01+0000/v0.45.0-0-gc3b4587b, go1.20.5, windows/amd64)
**Which OS you are running on your computer.**
- Windows 11
**The test script pointing to a publicly accessible website.**
`import { check } from 'k6';
import { chromium } from 'k6/experimental/browser';

export const options = {
    scenarios: {
        browser: {
            executor: 'per-vu-iterations',
            exec: 'browserTest',
            vus: 1
        }
    }
};
export async function browserTest() {
    const browser = chromium.launch({ headless: false });
    const page = browser.newPage();
    page.setViewportSize({
        width: 1366,
        height: 768
    });

    await page.goto('https://www.legalmatch.com/', { waitUntil: 'networkidle' });

    // Select Category
    const category = await page.locator("//button[normalize-space()='Choose a Category']");
    +category.click();

    const categoryToSelect = 'Family';
    const categoryItem = page.locator(
        `//div[@class='case-intake-form__dropdown-menu dropdown-menu js-case-intake-categories-dropdown is-single-choice']//div[normalize-space()='${categoryToSelect}']`
    );
    categoryItem.click();

    await page.locator('[aria-label="Zip Code or Locaton"]').fill('00001');
    await page.waitForSelector('.case-intake-form__location-checker--valid');
    const searchBtn = page.locator("//button[@data-aut='ci_submit-btn']");

    await Promise.all([page.waitForNavigation(60), searchBtn.click()]);

    // Select Sub Category
    const subCategory = 'Adoptions';
    page.locator(`//label[normalize-space()="${subCategory}"]`).click();

    await page.waitForTimeout(10000);

    // after this delay, we can repeat the same pattern as above:
    const nextBtn = page.locator("//button[@data-aut='ci_submit-btn']");

    await Promise.all([page.waitForNavigation(60), nextBtn.click()]);

    await page.waitForTimeout(10000);

    await Promise.all([page.waitForNavigation(60), nextBtn.click()]);
    await page.waitForTimeout(10000);

    // should now be on the "Describe your case" screen:
    check(page, {
        'description page loaded': () =>
            page.locator("//label[text()='Describe your Case in Detail:']").isVisible()
    });

    // Description
    await page.waitForSelector("input[placeholder='State why you need an attorney.']");
    await page.locator("input[placeholder='State why you need an attorney.']").fill('LoadTest');
    await page
        .locator(
            "textarea[placeholder='State the highlights / major facts that support your claim.']"
        )
        .fill('Test');

    await Promise.all([page.waitForNavigation(60), nextBtn.click()]);
    await page.waitForTimeout(3000);

    // Save Your Case
    await page.waitForSelector("input[name='firstName']");
    await page.locator("input[name='firstName']").fill('LoadTest');
    await page.locator("input[name='lastName']").fill('Test');
    await page.locator("input[(placeholder = '(555) 123-4567')]").fill('4354355345');
    await page.locator("input[name='email']").fill('none@legalmatch.com');
    await page.locator("input[(value = 'true')][(name = 'notifyBySms')]").click();
    await Promise.all([page.waitForNavigation(), nextBtn.click()]);
    await page.waitForTimeout(3000);

    page.close();
    browser.close();
}
`
**The exact error message you are seeing when you try and run the test.**
`ERRO[0030] communicating with browser: read tcp 127.0.0.1:51906->127.0.0.1:51905: wsarecv: An existing connection was forcibly closed by the remote host.  category=cdp elapsed="4970 ms" goroutine=73`

**Comment by ankur22** [comment] 2023-07-05 13:41
Follow the conversation in this [thread](https://community.k6.io/t/how-to-keep-the-browser-open/5747/10?u=ankur).
