### ISSUE TITLE
Provide typescript definitions

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#689] opened 2023-01-05 12:20 UTC
See this [example type definitions for k6](https://www.npmjs.com/package/@types/k6?activeTab=explore).

[Related community forum thread](https://community.k6.io/t/no-k6-x-browser-to-import/5557).

**Comment by inancgumus** [comment] 2023-01-06 12:56
Closing this as a duplicate of #282.

**Closed** 2023-01-12 07:41 UTC
Labels: duplicate, enhancement, user experience
